on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string
      image-name:
        required: true
        type: string
      docker-build-args:
        required: true
        type: string
      use-rust-caching:
        required: true
        type: boolean

jobs:
  build:
    permissions:
      packages: write

    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - uses: actions/cache@v4
        if: ${{ inputs.use-rust-caching }}
        with:
          path: app-target
          key: ${{ runner.os }}-app-target-${{ hashFiles('**/Cargo.lock') }}-${{ inputs.directory }}

      - uses: actions/cache@v4
        if: ${{ inputs.use-rust-caching }}
        with:
          path: cargo-registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}-${{ inputs.directory }}

      - uses: reproducible-containers/buildkit-cache-dance@v3.1.2
        if: ${{ inputs.use-rust-caching }}
        with:
          cache-map: |
            {
              "app-target": "/app/${{ inputs.directory }}-build/target/",
              "cargo-registry": "/usr/local/cargo/registry"
            }

      - name: Docker build
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: ${{ inputs.directory }}
          push: true
          tags: ghcr.io/accurate0/${{ inputs.image-name }}:latest,ghcr.io/accurate0/${{ inputs.image-name }}:${{ github.sha }}
          build-args: ${{ inputs.docker-build-args }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      # This ugly bit is necessary if you don't want your cache to grow forever
      # till it hits GitHub's limit of 5GB.
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
